#ifndef VERSION_H
#define VERSION_H

#define VER_INTERNALNAME_STR		"FPL_ImageViewer"
#define VER_PRODUCTNAME_STR			"FPL ImageViewer"
#define VER_PRODUCTVERSION          0,5,5,0
#define VER_PRODUCTVERSION_STR      "0.5.5\0"

#define VER_FILEVERSION             VER_PRODUCTVERSION
#define VER_FILEVERSION_STR         VER_PRODUCTVERSION_STR

#define VER_COMPANYNAME_STR			""
#define VER_FILEDESCRIPTION_STR		"A simple OpenGL based image viewer"
#define VER_LEGALCOPYRIGHT_STR		"Copyright (C) 2018-2020 Torsten Spaete"
#define VER_LEGALTRADEMARKS1_STR	""
#define VER_LEGALTRADEMARKS2_STR	""
#define VER_ORIGINALFILENAME_STR	VER_INTERNALNAME_STR ".exe"

#ifndef VOS_NT_WINDOWS32
#define VS_FF_DEBUG 0x00000001L
#define VS_FF_PRERELEASE 0x00000002L
#define VS_FF_PATCHED 0x00000004L
#define VS_FF_PRIVATEBUILD 0x00000008L
#define VS_FF_INFOINFERRED 0x00000010L
#define VS_FF_SPECIALBUILD 0x00000020L
#define VOS_NT_WINDOWS32 0x00040004L
#define VFT_APP 0x00000001L
#define VFT2_UNKNOWN 0x00000000L
#endif

#ifndef DEBUG
#define VER_DEBUG                   0
#else
#define VER_DEBUG                   VS_FF_DEBUG
#endif

#define VS_VERSION_INFO_XP 0
#define VS_VERSION_INFO_VISTA 1

#endif //VERSION_H
