/*
-------------------------------------------------------------------------------
Name:
	FPL Presentation FTD source

Description:
	Embedded copy of fpl_presentation.ftd as a C string literal so the FTD
	test suite does not depend on the current working directory.

	Regenerate by running, from this folder:
		python3 -c "..."  (see comments in ftd_test.c / project README)

Author:
	Torsten Spaete
-------------------------------------------------------------------------------
*/

#ifndef FPL_PRESENTATION_FTD_DATA_H
#define FPL_PRESENTATION_FTD_DATA_H

static const char fpl_presentation_ftd[] =
	"# =============================================================================\n"
	"# FPL Presentation - Final Text Data (FTD) format\n"
	"# See format.md in this folder for the full specification.\n"
	"#\n"
	"# Resources (fonts, sounds, images) are NOT declared in this file. They are\n"
	"# pre-registered by the host application under three groups:\n"
	"#   FontResources.<Name>     -> const FontResource *\n"
	"#   SoundResources.<Name>    -> const SoundResource *\n"
	"#   ImageResources.<Name>    -> const ImageResource *\n"
	"#\n"
	"# This file gathers those host-registered names into FTD namespaces (the\n"
	"# untyped `Name { ... }` blocks below) so the slides can refer to short,\n"
	"# grouped paths like `Cards.CPU` or `MyResources.sounds.Intro1` instead of\n"
	"# the long original `ImageResources.Card_CPU` / `SoundResources.Intro1`.\n"
	"# Namespaces are not parsed into any C struct - they live only in the\n"
	"# parser's symbol table and exist purely to organize references.\n"
	"# =============================================================================\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Type aliases\n"
	"# -----------------------------------------------------------------------------\n"
	"alias V2f = Vec2f\n"
	"alias V3f = Vec3f\n"
	"alias V4f = Vec4f\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Enum value aliases\n"
	"# -----------------------------------------------------------------------------\n"
	"alias Left   = HorizontalAlignment.Left\n"
	"alias Center = HorizontalAlignment.Center\n"
	"alias Right  = HorizontalAlignment.Right\n"
	"alias Top    = VerticalAlignment.Top\n"
	"alias Middle = VerticalAlignment.Middle\n"
	"alias Bottom = VerticalAlignment.Bottom\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Resource namespaces - group the host-registered globals so they are reachable\n"
	"# through short dotted paths.\n"
	"# -----------------------------------------------------------------------------\n"
	"Fonts {\n"
	"    Arimo             = FontResources.Arimo\n"
	"    BitStreamVerySans = FontResources.BitStreamVerySans\n"
	"}\n"
	"\n"
	"Cards {\n"
	"    CPU              = ImageResources.Card_CPU\n"
	"    Memory           = ImageResources.Card_Memory\n"
	"    C_Language       = ImageResources.Card_C_Language\n"
	"    Audio            = ImageResources.Card_Audio\n"
	"    Video            = ImageResources.Card_Video\n"
	"    WindowManagement = ImageResources.Card_WindowManagement\n"
	"    Performance      = ImageResources.Card_Performance\n"
	"    NoDependencies   = ImageResources.Card_NoDependencies\n"
	"    KeyboardMouse    = ImageResources.Card_KeyboardMouse\n"
	"    Gamepad          = ImageResources.Card_Gamepad\n"
	"}\n"
	"\n"
	"Misc {\n"
	"    MagicHat      = ImageResources.MagicHat\n"
	"    Arigatou      = ImageResources.Arigatou\n"
	"    MinimumSource = ImageResources.MinimumSource\n"
	"}\n"
	"\n"
	"Topics {\n"
	"    DataVisualization = ImageResources.DataVisualization\n"
	"    GameDev           = ImageResources.GameDev\n"
	"    MultimediaDev     = ImageResources.MultimediaDev\n"
	"    SimulationDev     = ImageResources.SimulationDev\n"
	"    Code              = ImageResources.Code\n"
	"}\n"
	"\n"
	"Vendors {\n"
	"    FreeBSD   = ImageResources.Vendor_FreeBSD\n"
	"    Linux     = ImageResources.Vendor_Linux\n"
	"    Windows   = ImageResources.Vendor_Windows\n"
	"    Raspberry = ImageResources.Vendor_Raspberry\n"
	"    OpenGL    = ImageResources.Vendor_OpenGL\n"
	"    Vulkan    = ImageResources.Vendor_Vulkan\n"
	"    DirectX   = ImageResources.Vendor_DirectX\n"
	"    Alsa      = ImageResources.Vendor_Alsa\n"
	"    XLib      = ImageResources.Vendor_XLib\n"
	"}\n"
	"\n"
	"Demos {\n"
	"    ImGUI           = ImageResources.Demo_ImGUI\n"
	"    FFMPEG          = ImageResources.Demo_FFMPEG\n"
	"    NBodySimulation = ImageResources.Demo_NBodySimulation\n"
	"    Audio           = ImageResources.Demo_Audio\n"
	"    Input           = ImageResources.Demo_Input\n"
	"    Crackout        = ImageResources.Demo_Crackout\n"
	"    OpenGL          = ImageResources.Demo_OpenGL\n"
	"    Raytracer       = ImageResources.Demo_Raytracer\n"
	"}\n"
	"\n"
	"HowItWorksIcons {\n"
	"    SingleHeaderFile  = ImageResources.Feature_SingleHeaderFile\n"
	"    RuntimeLinking    = ImageResources.Feature_RuntimeLinking\n"
	"    PreProcessor      = ImageResources.Feature_PreProcessor\n"
	"    NoCodeDuplication = ImageResources.Feature_NoCodeDuplication\n"
	"}\n"
	"\n"
	"Sounds {\n"
	"    Intro1     = SoundResources.Intro1\n"
	"    Intro2     = SoundResources.Intro2\n"
	"    WhoAmi1    = SoundResources.WhoAmi1\n"
	"    What1      = SoundResources.What1\n"
	"    What2      = SoundResources.What2\n"
	"    Motivation = SoundResources.Motivation\n"
	"}\n"
	"\n"
	"# A top-level umbrella that bundles the per-category namespaces, reached via\n"
	"# nested dotted paths like `MyResources.sounds.Intro1`. The members are\n"
	"# themselves namespace references — accessing a deeper member transparently\n"
	"# folds through this layer.\n"
	"MyResources {\n"
	"    fonts   = Fonts\n"
	"    cards   = Cards\n"
	"    misc    = Misc\n"
	"    topics  = Topics\n"
	"    vendors = Vendors\n"
	"    demos   = Demos\n"
	"    icons   = HowItWorksIcons\n"
	"    sounds  = Sounds\n"
	"}\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# File-local constants\n"
	"# -----------------------------------------------------------------------------\n"
	"float CodeFontSize     = 24.0\n"
	"float FeaturesFontSize = 32.0\n"
	"float HeaderFontSize   = 24.0\n"
	"float TitleFontSize    = 64.0\n"
	"float NormalFontSize   = 42.0\n"
	"float ConsoleFontSize  = 36.0\n"
	"float DefaultLineScale = 1.15\n"
	"\n"
	"V4f White        = V4f(1, 1, 1, 1)\n"
	"V4f Black        = V4f(0, 0, 0, 1)\n"
	"V4f WhiteHalf    = V4f(1, 1, 1, 0.5)\n"
	"V4f WhiteSoft    = V4f(1, 1, 1, 0.85)\n"
	"V4f WhiteFaint   = V4f(1, 1, 1, 0.65)\n"
	"V4f WhiteGhost   = V4f(1, 1, 1, 0.05)\n"
	"V4f LinkGreen    = V4f(0.0, 0.8, 0.2, 1.0)\n"
	"\n"
	"V2f TextShadowOffset = V2f(2, 1)\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Backgrounds (HalfGradientHorizontal: primary -> secondary)\n"
	"# RGBA24(hex, alpha) and RGBA(r,g,b,a) return linear-space Vec4f.\n"
	"# -----------------------------------------------------------------------------\n"
	"BackgroundStyle FixedBackground { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x0483AF, 100) }\n"
	"BackgroundStyle DarkBlueBack    { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA(15, 13, 80, 255) }\n"
	"\n"
	"# DarkBlue -> LightBlue\n"
	"BackgroundStyle Background1  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x333789, 100) }\n"
	"BackgroundStyle Background2  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x1E5AA3, 100) }\n"
	"BackgroundStyle Background3  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x0483AF, 100) }\n"
	"\n"
	"# Green -> Yellow\n"
	"BackgroundStyle Background4  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x057F47, 100) }\n"
	"BackgroundStyle Background5  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x7AB30B, 100) }\n"
	"BackgroundStyle Background6  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xF2E500, 100) }\n"
	"\n"
	"# LightOrange -> DarkOrange\n"
	"BackgroundStyle Background7  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xFDBD00, 100) }\n"
	"BackgroundStyle Background8  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xEE7B00, 100) }\n"
	"BackgroundStyle Background9  { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xE54B0A, 100) }\n"
	"BackgroundStyle Background10 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xE54B0A, 200) }\n"
	"\n"
	"# Red -> Purple\n"
	"BackgroundStyle Background11 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xDC0012, 100) }\n"
	"BackgroundStyle Background12 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0xB7006A, 100) }\n"
	"BackgroundStyle Background13 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x59227A, 100) }\n"
	"\n"
	"# Purple -> Brown\n"
	"BackgroundStyle Background14 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x237b75, 100) }\n"
	"BackgroundStyle Background15 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x6d7b23, 100) }\n"
	"BackgroundStyle Background16 { kind = HalfGradientHorizontal  primaryColor = RGBA24(0x000000, 255)  secondaryColor = RGBA24(0x7b5223, 100) }\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Text styles\n"
	"# -----------------------------------------------------------------------------\n"
	"TextStyle BasicStyle {\n"
	"    foregroundColor = White\n"
	"    shadowColor     = Black\n"
	"    shadowOffset    = TextShadowOffset\n"
	"    drawShadow      = true\n"
	"}\n"
	"\n"
	"TextStyle HeaderStyle {\n"
	"    foregroundColor = White\n"
	"    shadowColor     = Black\n"
	"    shadowOffset    = V2f(1, 1)\n"
	"    drawShadow      = true\n"
	"}\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Slides\n"
	"# -----------------------------------------------------------------------------\n"
	"\n"
	"Slide Intro {\n"
	"    title    = \"Introduction\"\n"
	"    duration = 18.5\n"
	"    rotation = { angleDegrees = 0.0, axis = V3f(1, 1, 1) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"Hi! I am Torsten\"\n"
	"           \"Today, i would like to introduce you to a project of mine that i have been working on for several years\"\n"
	"           \"It is called 'Final Platform Layer' or short FPL and is a platform abstraction library for C and C++\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"Introducing Final-Platform-Layer (FPL)\\n\"\n"
	"                            \"A lightweight platform abstraction library written in C99\\n\"\n"
	"                textAlign = Center\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"\n"
	"    sounds = [\n"
	"        { name = MyResources.sounds.Intro1, startTime = 1.0  }\n"
	"        { name = MyResources.sounds.Intro2, startTime = 10.0 }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide WhoAmI {\n"
	"    title    = \"Who am I\"\n"
	"    duration = 20.5\n"
	"    rotation = { angleDegrees = 15.0, axis = V3f(1, 1, 1) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"I am Torsten Spaete\"\n"
	"           \"A professional software engineer with more than 25 years of programming experience\"\n"
	"           \"My main focus is data-visualization, software-architecture, multimedia and game development\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(0.45, 0.45)\n"
	"            contentAlignment = { h = Left, v = Top }\n"
	"            image {\n"
	"                imageResource = Topics.DataVisualization\n"
	"                size       = V2f(1.0, 1.0)\n"
	"                keepAspect = true\n"
	"                tintColor  = WhiteHalf\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.55, 0.0)\n"
	"            size = V2f(0.45, 0.45)\n"
	"            contentAlignment = { h = Right, v = Top }\n"
	"            image {\n"
	"                imageResource = Topics.MultimediaDev\n"
	"                size       = V2f(1.0, 1.0)\n"
	"                keepAspect = true\n"
	"                tintColor  = WhiteHalf\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.0, 0.50)\n"
	"            size = V2f(0.45, 0.45)\n"
	"            contentAlignment = { h = Left, v = Bottom }\n"
	"            image {\n"
	"                imageResource = Topics.SimulationDev\n"
	"                size       = V2f(1.0, 1.0)\n"
	"                keepAspect = true\n"
	"                tintColor  = WhiteHalf\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.55, 0.50)\n"
	"            size = V2f(0.45, 0.45)\n"
	"            contentAlignment = { h = Right, v = Bottom }\n"
	"            image {\n"
	"                imageResource = Topics.GameDev\n"
	"                size       = V2f(1.0, 1.0)\n"
	"                keepAspect = true\n"
	"                tintColor  = WhiteHalf\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"I am Torsten Spaete\\n\"\n"
	"                            \"A professional software engineer\\n\"\n"
	"                            \"25+ years of programming experience\\n\"\n"
	"                textAlign = Center\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"\n"
	"    sounds = [\n"
	"        { name = MyResources.sounds.WhoAmi1, startTime = 2.0 }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide WhatIsFPL {\n"
	"    title    = \"What is FPL\"\n"
	"    duration = 33.0\n"
	"    rotation = { angleDegrees = -45.0, axis = V3f(0, 1, 1) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"Final-Platform-Layer (or short 'FPL') is a lightweight platform-abstraction library written in C99,\"\n"
	"           \"that gives you access to low-level systems, hardware devices and operating system functions,\"\n"
	"           \"in a platform independent and easy-to-use API.\"\n"
	"           \"\"\n"
	"           \"For example you can:\"\n"
	"           \"- Play audio samples on any audio device\"\n"
	"           \"- Create and manage windows, including the initialization of a video graphics api, such as OpenGL, Vulkan\"\n"
	"           \"- Query keyboard, mouse and gamepad input\"\n"
	"           \"- Execute code in parallel, using several multithreading techniques\"\n"
	"           \"- Allocate and free memory directly on the platform, without the use of malloc or free\"\n"
	"           \"- Modify and query files & directories\"\n"
	"           \"- Query several platform and hardware informations\"\n"
	"           \"- and much more\"\n"
	"           \"\"\n"
	"           \"Its main usage is multimedia and game development, but it can be used to write any kind of software.\"\n"
	"           \"'FPL' is designed to be fast in compile and run time and can be integrated however you like.\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.0, -0.1)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            image {\n"
	"                imageResource = Topics.Code\n"
	"                size       = V2f(1.0, 1.2)\n"
	"                keepAspect = false\n"
	"                tintColor  = WhiteGhost\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"Final-Platform-Layer (or short 'FPL')\\n\"\n"
	"                            \"is a lightweight library written in C99 with support for C++.\\n\"\n"
	"                            \"\\n\"\n"
	"                            \"It provides a powerful and easy to use API,\\n\"\n"
	"                            \"that gives you access to low-level systems, hardware devices,\\n\"\n"
	"                            \"operating system functions and many more.\"\n"
	"                textAlign = Left\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"\n"
	"    sounds = [\n"
	"        { name = MyResources.sounds.What1, startTime = 1.0  }\n"
	"        { name = MyResources.sounds.What2, startTime = 17.0 }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Motivation {\n"
	"    title    = \"Motivation\"\n"
	"    duration = 31.0\n"
	"    rotation = { angleDegrees = 70.0, axis = V3f(1.0, 0.1, 0.0) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"C/C++ has very limited access to the underlying platform.\"\n"
	"           \"Even in modern C++, you still don't have direct access to a lot of systems.\"\n"
	"           \"To access low-level systems, such as audio or video or windowing systems, you either need to use third-party libraries\"\n"
	"           \"or write platform-specific code directly for every platform you want to support.\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"C/C++ has very limited access to the underlying platform,\\n\"\n"
	"                            \"so you either have to use third-party libraries or\\n\"\n"
	"                            \"write platform specific code directly.\\n\"\n"
	"                textAlign = Left\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"\n"
	"    sounds = [\n"
	"        { name = MyResources.sounds.Motivation, startTime = 2.0 }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Features {\n"
	"    title    = \"Features\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 30.0, axis = V3f(0.0, 1.0, 0.1) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"FPL was designed to make the creation of multimedia applications or games very easy.\"\n"
	"           \"\"\n"
	"           \"- It can create and manage a window for you, including the handling of events\"\n"
	"           \"- It can handle keyboard & mouse devices\"\n"
	"           \"- It can handle gamepads as well\"\n"
	"           \"- It can initialize a graphics backend for you, such as OpenGL, Vulkan or allows you to put pixels directly on the screen\"\n"
	"           \"- It can play back sound samples asynchrously\"\n"
	"           \"- It is written in C99 for simplicity and best portability, but is 100% c++ compatible\"\n"
	"           \"- It is designed to be fast in compile and runtime\"\n"
	"           \"- It does not require any build-systems or thirdparty libraries\"\n"
	"           \"- It gives you control of memory allocations and handles memory very gracefully\"\n"
	"           \"- It supports the major architectures: X86, X64 and ARM\"\n"
	"           \"- It supports many compilers and platforms and provides useful utilities fo work with them\"\n"
	"           \"- It is highly configurable and many features can be compiled out, if needed\"\n"
	"           \"- It provides useful primitives to create code that runs on different threads\"\n"
	"           \"- In addition it contains a ton of useful functions and macros\"\n"
	"\n"
	"    blocks = [\n"
	"        # Row 1 - cards\n"
	"        { type = Image  pos = V2f(0.0, 0.1)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.WindowManagement  size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.2, 0.1)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.KeyboardMouse     size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.4, 0.1)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.Gamepad           size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.6, 0.1)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.Video             size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.8, 0.1)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.Audio             size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"\n"
	"        # Row 1 - labels\n"
	"        { type = Text  pos = V2f(0.0, 0.3)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Window Management\"    textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.2, 0.3)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Input Handling\"       textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.4, 0.3)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Gamepad Support\"      textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.6, 0.3)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Video Initialization\" textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.8, 0.3)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Audio Playback\"       textAlign = Left  fontSize = 20.0 } }\n"
	"\n"
	"        # Row 2 - cards\n"
	"        { type = Image  pos = V2f(0.0, 0.55)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.C_Language      size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.2, 0.55)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.Performance     size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.4, 0.55)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.NoDependencies  size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.6, 0.55)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.Memory          size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.8, 0.55)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Top }  image { imageResource = Cards.CPU             size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"\n"
	"        # Row 2 - labels\n"
	"        { type = Text  pos = V2f(0.0, 0.75)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Written in C99\"         textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.2, 0.75)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"High Performance\"       textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.4, 0.75)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"No Dependencies\"        textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.6, 0.75)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Small Memory Footprint\" textAlign = Left  fontSize = 20.0 } }\n"
	"        { type = Text  pos = V2f(0.8, 0.75)  size = V2f(0.2, 0.1)  contentAlignment = { h = Center, v = Top }  text { text = \"Architecture Support\"   textAlign = Left  fontSize = 20.0 } }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Platforms {\n"
	"    title    = \"Supported Platforms\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 75.0, axis = V3f(-0.5, 0.65, 0.5) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"FPL supports the major operating systems, such as Windows, Linux, Raspberry Pi and Unix or BSD\"\n"
	"\n"
	"    blocks = [\n"
	"        { type = Image  pos = V2f(0.0, 0.2)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.Windows    size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.1, 0.2)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.Linux      size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.2, 0.2)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.Raspberry  size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.3, 0.2)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.FreeBSD    size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.4, 0.6)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.OpenGL     size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.5, 0.6)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.Vulkan     size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.6, 0.6)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.DirectX    size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.7, 0.6)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.Alsa       size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.8, 0.6)  size = V2f(0.2, 0.2)  contentAlignment = { h = Center, v = Bottom }  image { imageResource = Vendors.XLib       size = V2f(1, 1)  keepAspect = true  tintColor = White } }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Magic {\n"
	"    title    = \"How it works\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = -15.0, axis = V3f(0.7, 0.6, 0.3) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"It works with Magic!\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(-0.15, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            image {\n"
	"                imageResource = Misc.MagicHat\n"
	"                size       = V2f(0.75, 0.75)\n"
	"                keepAspect = true\n"
	"                tintColor  = White\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"Magic!\"\n"
	"                textAlign = Left\n"
	"                fontSize  = 128.0\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide HowItWorks {\n"
	"    title    = \"How it actually works\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 45.0, axis = V3f(0.5, 0.5, 0.5) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"Of course, there is no magic involved - it uses just a few tricks.\"\n"
	"           \"\"\n"
	"           \"FPL is a 'single-header-file-library', so it contains the full header or API and implementation for every platform in a single C file\"\n"
	"           \"It makes heavy use of the pre-processor to detect compiler/platform/hardware/driver setups\"\n"
	"           \"It prevents code duplication by using sub platforms\"\n"
	"           \"It uses runtime linking by default, so everything is automatically loaded on demand\"\n"
	"\n"
	"    blocks = [\n"
	"        { type = Image  pos = V2f(0.05, 0.125)  size = V2f(0.15, 0.65)  contentAlignment = { h = Left, v = Middle }  image { imageResource = HowItWorksIcons.SingleHeaderFile   size = V2f(1, 1)  keepAspect = false  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.30, 0.125)  size = V2f(0.15, 0.65)  contentAlignment = { h = Left, v = Middle }  image { imageResource = HowItWorksIcons.PreProcessor       size = V2f(1, 1)  keepAspect = false  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.55, 0.125)  size = V2f(0.15, 0.65)  contentAlignment = { h = Left, v = Middle }  image { imageResource = HowItWorksIcons.NoCodeDuplication  size = V2f(1, 1)  keepAspect = false  tintColor = White } }\n"
	"        { type = Image  pos = V2f(0.80, 0.125)  size = V2f(0.15, 0.65)  contentAlignment = { h = Left, v = Middle }  image { imageResource = HowItWorksIcons.RuntimeLinking     size = V2f(1, 1)  keepAspect = false  tintColor = White } }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Constraints {\n"
	"    title    = \"Constraints\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 65.0, axis = V3f(0.0, 0.5, 1.0) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"FPL is lightweight, so the feature set is limited. As a result, you'll need to provide some functionality.\"\n"
	"           \"\"\n"
	"           \"Video rendering is intentionally excluded, giving users the flexibility to integrate their own solutions\"\n"
	"           \"\"\n"
	"           \"Audio sample conversion is intentionally excluded, giving users the flexibility to integrate their own solutions\"\n"
	"           \"\"\n"
	"           \"Platform support are limited to X86 or ARM, both with support for 32-bit or 64-bit\"\n"
	"           \"More platforms may be added in the future, such as MacOS, Android or server-based platforms.\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.0)\n"
	"            size = V2f(1.0, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"- Video rendering must be provided yourself\\n\"\n"
	"                            \"\\n\"\n"
	"                            \"- Audio sample conversion must be provided yourself\\n\"\n"
	"                            \"\\n\"\n"
	"                            \"Platform support are constrained to:\\n\"\n"
	"                            \"- X86/X64/ARM32/ARM64\\n\"\n"
	"                            \"- Windows/Linux/Unix\\n\"\n"
	"                textAlign = Left\n"
	"                fontSize  = 40.0\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide HowToUse {\n"
	"    title    = \"How to use\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 75.0, axis = V3f(0.0, 1.0, 0.0) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.075, 0.0)\n"
	"            size = V2f(0.85, 1.0)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            image {\n"
	"                imageResource = Misc.MinimumSource\n"
	"                size       = V2f(1.0, 1.0)\n"
	"                keepAspect = false\n"
	"                tintColor  = WhiteSoft\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Demos {\n"
	"    title    = \"Demos!\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = -45.0, axis = V3f(1.0, 0.5, 0.25) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"FPL comes with a lot of fully working demos, so you can learn how it works.\"\n"
	"\n"
	"    blocks = [\n"
	"        { type = Image  pos = V2f(0.00, 0.0)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.ImGUI            size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.25, 0.0)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.FFMPEG           size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.50, 0.0)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.Audio            size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.75, 0.0)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.Input            size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.00, 0.6)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.OpenGL           size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.25, 0.6)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.Crackout         size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.50, 0.6)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.Raytracer        size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"        { type = Image  pos = V2f(0.75, 0.6)  size = V2f(0.25, 0.25)  contentAlignment = { h = Center, v = Middle }  image { imageResource = Demos.NBodySimulation  size = V2f(1, 1)  keepAspect = true  tintColor = WhiteFaint } }\n"
	"\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.3)\n"
	"            size = V2f(1.0, 0.1)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"FPL comes with a variety of demos:\"\n"
	"                textAlign = Center\n"
	"                fontSize  = FeaturesFontSize\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.0, 0.4)\n"
	"            size = V2f(1.0, 0.1)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"https://github.com/f1nalspace/final_game_tech/tree/master/demos\"\n"
	"                textAlign = Center\n"
	"                fontSize  = FeaturesFontSize\n"
	"                color     = LinkGreen\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Links {\n"
	"    title    = \"Links\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 65.0, axis = V3f(1, 0, 0) }\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"If you are interested about learning more about FPL, you can visit the official website: libfpl.org\"\n"
	"           \"\"\n"
	"           \"Or go to the github repository directly\"\n"
	"           \"\"\n"
	"           \"If you are watching this presentation over a streaming platform, you can also find all the links in the description below.\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.25, 0.0)  size = V2f(0.5, 0.1)\n"
	"            contentAlignment = { h = Left, v = Middle }\n"
	"            text { text = \"Official website (details, releases, documentation):\"  textAlign = Left  fontSize = FeaturesFontSize }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.25, 0.1)  size = V2f(0.5, 0.1)\n"
	"            contentAlignment = { h = Left, v = Middle }\n"
	"            text { text = \"https://libfpl.org\"  textAlign = Left  fontSize = FeaturesFontSize  color = LinkGreen }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.25, 0.3)  size = V2f(0.5, 0.1)\n"
	"            contentAlignment = { h = Left, v = Middle }\n"
	"            text { text = \"Github (sources, issue-tracker, project management):\"  textAlign = Left  fontSize = FeaturesFontSize }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.25, 0.4)  size = V2f(0.5, 0.1)\n"
	"            contentAlignment = { h = Left, v = Middle }\n"
	"            text { text = \"https://github.com/f1nalspace/final_game_tech\"  textAlign = Left  fontSize = FeaturesFontSize  color = LinkGreen }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.25, 0.6)  size = V2f(0.5, 0.1)\n"
	"            contentAlignment = { h = Left, v = Middle }\n"
	"            text { text = \"Handmade-Network (community):\"  textAlign = Left  fontSize = FeaturesFontSize }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0.25, 0.7)  size = V2f(0.5, 0.1)\n"
	"            contentAlignment = { h = Left, v = Middle }\n"
	"            text { text = \"https://fpl.handmade.network\"  textAlign = Left  fontSize = FeaturesFontSize  color = LinkGreen }\n"
	"        }\n"
	"    ]\n"
	"}\n"
	"\n"
	"Slide Thanks {\n"
	"    title    = \"Thanks!\"\n"
	"    duration = 0.0\n"
	"    rotation = { angleDegrees = 0.0, axis = V3f(1, 1, 1) }   # 0 deg => identity quaternion\n"
	"    background = FixedBackground\n"
	"\n"
	"    talk = \"Thank you for watching this presentation and i hope you will give FPL a try.\"\n"
	"           \"\"\n"
	"           \"Feel free to post any questions or feedback on github or if possible, as a comment to this video.\"\n"
	"           \"\"\n"
	"           \"As always, keep coding!\"\n"
	"\n"
	"    blocks = [\n"
	"        {\n"
	"            type = Image\n"
	"            pos  = V2f(0.4, 0.4)  size = V2f(0.6, 0.6)\n"
	"            contentAlignment = { h = Right, v = Bottom }\n"
	"            image {\n"
	"                imageResource = Misc.Arigatou\n"
	"                size       = V2f(1.0, 1.0)\n"
	"                keepAspect = true\n"
	"                tintColor  = WhiteFaint\n"
	"            }\n"
	"        }\n"
	"        {\n"
	"            type = Text\n"
	"            pos  = V2f(0, 0)  size = V2f(1, 1)\n"
	"            contentAlignment = { h = Center, v = Middle }\n"
	"            text {\n"
	"                text      = \"Thank you for your attention!\"\n"
	"                textAlign = Center\n"
	"            }\n"
	"        }\n"
	"    ]\n"
	"}\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Header / Footer\n"
	"# -----------------------------------------------------------------------------\n"
	"HeaderDefinition Header {\n"
	"    font {\n"
	"        name      = Fonts.Arimo           # via Fonts namespace\n"
	"        size      = HeaderFontSize\n"
	"        lineScale = DefaultLineScale\n"
	"        style     = HeaderStyle\n"
	"    }\n"
	"    height     = 32.0\n"
	"    leftText   = \"Final-Platform-Layer\"\n"
	"    centerText = \"\"\n"
	"    rightText  = \"\"\n"
	"    padding    = V2f(2, 2)\n"
	"}\n"
	"\n"
	"FooterDefinition Footer {\n"
	"    font {\n"
	"        name      = Fonts.Arimo\n"
	"        size      = HeaderFontSize\n"
	"        lineScale = DefaultLineScale\n"
	"        style     = HeaderStyle\n"
	"    }\n"
	"    height     = 32.0\n"
	"    leftText   = \"%SLIDE_NAME%\"\n"
	"    centerText = \"Copyright (C) 2017-2025 Torsten Spaete\"\n"
	"    rightText  = \"Page %SLIDE_NUM% of %SLIDE_COUNT%\"\n"
	"    padding    = V2f(2, 3)\n"
	"}\n"
	"\n"
	"# -----------------------------------------------------------------------------\n"
	"# Presentation root - the entry point a loader should resolve\n"
	"# -----------------------------------------------------------------------------\n"
	"Presentation FPLPresentation {\n"
	"    slideSize = V2f(1280.0, 720.0)\n"
	"    padding   = 20.0\n"
	"\n"
	"    slides = [\n"
	"        Intro\n"
	"        WhoAmI\n"
	"        WhatIsFPL\n"
	"        Motivation\n"
	"        Features\n"
	"        Platforms\n"
	"        Magic\n"
	"        HowItWorks\n"
	"        Constraints\n"
	"        HowToUse\n"
	"        Demos\n"
	"        Links\n"
	"        Thanks\n"
	"    ]\n"
	"\n"
	"    header = Header\n"
	"    footer = Footer\n"
	"\n"
	"    titleFont   { name = MyResources.fonts.Arimo              size = TitleFontSize    lineScale = DefaultLineScale  style = BasicStyle }\n"
	"    normalFont  { name = MyResources.fonts.Arimo              size = NormalFontSize   lineScale = DefaultLineScale  style = BasicStyle }\n"
	"    consoleFont { name = MyResources.fonts.BitStreamVerySans  size = ConsoleFontSize  lineScale = DefaultLineScale  style = BasicStyle }\n"
	"}\n";
#endif // FPL_PRESENTATION_FTD_DATA_H
