/*
-------------------------------------------------------------------------------
Name:
	GamepadDB Generator

Description:
	Offline tool that reads an SDL gamecontrollerdb.txt file, parses every
	mapping line via fplParseGameControllerMappingLine, sorts the resulting
	entries by raw GUID, and emits a C header file that contains the
	precompiled binary blob:

		const uint8_t fpl__g_gamepadMappingTable[];

	The blob layout is the one documented in gamecontrollerdb_parser.c
	(u32 LE entryCount header followed by 57-byte fixed-size entries).

Usage:
	gamepaddbgen <input gamecontrollerdb.txt> <output header.h> [symbol-name]

	Default symbol name: fpl__g_gamepadMappingTable

Build:
	The parser source is included directly (unity build), so just compile
	this single translation unit.

Requirements:
	- C99 Compiler
	- Final Platform Layer (used by the parser)
-------------------------------------------------------------------------------
*/

#define FPL_IMPLEMENTATION
#define FPL_NO_WINDOW
#include <final_platform_layer.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "parser.c"

static int CompareMappingsByGuid(const void *a, const void *b) {
	const fplGamepadMapping *ma = (const fplGamepadMapping *)a;
	const fplGamepadMapping *mb = (const fplGamepadMapping *)b;
	return memcmp(ma->guid, mb->guid, FPL_GAMEPAD_GUID_BYTES);
}

int main(int argc, char **argv) {
	if (argc < 3) {
		fprintf(stderr, "Usage: %s <gamecontrollerdb.txt> <output.h> [symbol-name]\n", argv[0]);
		return 1;
	}
	const char *inputPath = argv[1];
	const char *outputPath = argv[2];
	const char *symbolName = (argc >= 4) ? argv[3] : "fpl__g_gamepadMappingTable";

	FILE *in = fopen(inputPath, "rb");
	if (in == NULL) {
		fprintf(stderr, "Failed to open input '%s'\n", inputPath);
		return 1;
	}

	size_t cap = 4096;
	size_t count = 0;
	fplGamepadMapping *entries = (fplGamepadMapping *)malloc(cap * sizeof(fplGamepadMapping));
	if (entries == NULL) { fclose(in); return 1; }

	char line[2048];
	uint32_t lineNumber = 0;
	uint32_t skippedComments = 0;
	uint32_t skippedMalformed = 0;
	while (fgets(line, sizeof(line), in) != NULL) {
		++lineNumber;
		// Quick skip to keep error counts honest.
		if (line[0] == '\0' || line[0] == '\n' || line[0] == '\r' || line[0] == '#') {
			++skippedComments;
			continue;
		}
		fplGamepadMapping m;
		if (!fplParseGameControllerMappingLine(line, &m)) {
			++skippedMalformed;
			continue;
		}
		if (count == cap) {
			cap *= 2;
			fplGamepadMapping *grown = (fplGamepadMapping *)realloc(entries, cap * sizeof(fplGamepadMapping));
			if (grown == NULL) { free(entries); fclose(in); return 1; }
			entries = grown;
		}
		entries[count++] = m;
	}
	fclose(in);

	qsort(entries, count, sizeof(fplGamepadMapping), CompareMappingsByGuid);

	size_t blobSize = count * FPL_GAMEPAD_BLOB_ENTRY_SIZE;
	uint8_t *blob = (uint8_t *)malloc(blobSize == 0 ? 1 : blobSize);
	if (blob == NULL) { free(entries); return 1; }

	for (size_t i = 0; i < count; ++i) {
		fplEncodeGamepadMappingEntry(&entries[i], blob + i * FPL_GAMEPAD_BLOB_ENTRY_SIZE);
	}

	FILE *out = fopen(outputPath, "wb");
	if (out == NULL) {
		fprintf(stderr, "Failed to open output '%s'\n", outputPath);
		free(blob);
		free(entries);
		return 1;
	}

	// Pad the blob up to a multiple of 8 with zero bytes so it can be stored
	// as a uint64_t array (each word holds 8 bytes packed little-endian).
	size_t paddedSize = (blobSize + 7u) & ~(size_t)7u;
	size_t wordCount = paddedSize / 8u;

	fprintf(out, "// Auto-generated by gamepaddbgen. Do not edit.\n");
	fprintf(out, "// Source: %s\n", inputPath);
	fprintf(out, "// Entries: %u, blob size: %zu bytes (entry size: %d), padded: %zu bytes / %zu uint64_t words.\n",
		(unsigned)count, blobSize, FPL_GAMEPAD_BLOB_ENTRY_SIZE, paddedSize, wordCount);
	fprintf(out, "//\n");
	fprintf(out, "// Layout (byte stream view) - %u entries, no embedded header:\n", (unsigned)count);
	fprintf(out, "//   per entry (%d bytes), sorted by raw GUID:\n", FPL_GAMEPAD_BLOB_ENTRY_SIZE);
	fprintf(out, "//     [16 B]                 GUID\n");
	fprintf(out, "//     [ 1 B]                 platform\n");
	fprintf(out, "//     [%d x u16 LE]          bindings (buttons then axes)\n",
		FPL_GAMEPAD_BINDING_COUNT);
	fprintf(out, "//\n");
	fprintf(out, "// Each uint64_t word packs 8 consecutive bytes in little-endian order,\n");
	fprintf(out, "// i.e. byte[i] = (word[i/8] >> ((i %% 8) * 8)) & 0xFF.\n");
	fprintf(out, "// Tail bytes past the actual blob size are zero-padded.\n");
	fprintf(out, "\n");
	fprintf(out, "#pragma once\n\n");
	fprintf(out, "#include <stdint.h>\n");
	fprintf(out, "#include <stddef.h>\n\n");
	fprintf(out, "#define FPL_GAMEPAD_MAPPING_TABLE_ENTRY_COUNT %uu\n", (unsigned)count);
	fprintf(out, "#define FPL_GAMEPAD_MAPPING_TABLE_SIZE         %zuu\n", blobSize);
	fprintf(out, "#define FPL_GAMEPAD_MAPPING_TABLE_U64_COUNT    %zuu\n\n", wordCount);
	fprintf(out, "static const uint64_t %s[FPL_GAMEPAD_MAPPING_TABLE_U64_COUNT] = {\n", symbolName);

	const size_t wordsPerLine = 6;
	for (size_t w = 0; w < wordCount; ++w) {
		uint64_t word = 0;
		for (size_t b = 0; b < 8; ++b) {
			size_t byteIndex = w * 8 + b;
			uint8_t v = (byteIndex < blobSize) ? blob[byteIndex] : 0u;
			word |= (uint64_t)v << (b * 8);
		}
		if ((w % wordsPerLine) == 0) fprintf(out, "\t");
		fprintf(out, "0x%016llXu", (unsigned long long)word);
		if (w + 1 < wordCount) fprintf(out, ",");
		if ((w % wordsPerLine) == wordsPerLine - 1 || w + 1 == wordCount) fprintf(out, "\n");
		else fprintf(out, " ");
	}
	fprintf(out, "};\n");
	fclose(out);

	fprintf(stdout, "Wrote %zu entries (%zu bytes) to %s\n", count, blobSize, outputPath);
	fprintf(stdout, "  comments/blank skipped: %u\n", skippedComments);
	fprintf(stdout, "  malformed skipped:      %u\n", skippedMalformed);

	free(blob);
	free(entries);
	return 0;
}
