#ifndef SHADERS_H
#define SHADERS_H

static const char g_shaderVertexPosTexcoord[] = {
	"varying vec2 vTexCoord;\n"
	"void main() {\n"
	"	gl_Position = ftransform();\n"
	"   vTexCoord = gl_MultiTexCoord0.xy;\n"
	"	gl_TexCoord[0] = gl_MultiTexCoord0;\n"
	"}\n"
};

static const char g_shaderFragmentTextureColor[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"void main() {\n"
	"   vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"	vec3 color = texture2D(textureSampler, textureUV).rgb;\n"
	"	gl_FragColor = vec4(color, 1.0);\n"
	"}\n"
};

static const char g_shaderFragmentTextureBilinear[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"void main() {\n"
	"   vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"	vec2 texelSize = 1.0 / textureSize;\n"
	"	vec2 texelPos = textureUV * textureSize - 0.5;\n"
	"	vec2 baseTexel = floor(texelPos);\n"
	"	vec2 blend = fract(texelPos);\n"
	"	vec2 uv00 = (baseTexel + vec2(0.5, 0.5)) * texelSize;\n"
	"	vec2 uv10 = (baseTexel + vec2(1.5, 0.5)) * texelSize;\n"
	"	vec2 uv01 = (baseTexel + vec2(0.5, 1.5)) * texelSize;\n"
	"	vec2 uv11 = (baseTexel + vec2(1.5, 1.5)) * texelSize;\n"
	"	vec4 color00 = texture2D(textureSampler, uv00);\n"
	"	vec4 color10 = texture2D(textureSampler, uv10);\n"
	"	vec4 color01 = texture2D(textureSampler, uv01);\n"
	"	vec4 color11 = texture2D(textureSampler, uv11);\n"
	"	vec4 colorX0 = mix(color00, color10, blend.x);\n"
	"	vec4 colorX1 = mix(color01, color11, blend.x);\n"
	"	vec4 color = mix(colorX0, colorX1, blend.y);\n"
	"	gl_FragColor = color;\n"
	"}\n"
};

static const char g_shaderFragmentTextureCatmullRom[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"\n"
	"float CatmullRomWeight(float x) {\n"
	"	x = abs(x);\n"
	"	if (x <= 1.0) {\n"
	"		return 1.5 * x * x * x - 2.5 * x * x + 1.0;\n"
	"	} else if (x < 2.0) {\n"
	"		return -0.5 * x * x * x + 2.5 * x * x - 4.0 * x + 2.0;\n"
	"	}\n"
	"	return 0.0;\n"
	"}\n"
	"\n"
	"vec4 SampleTextureCatmullRom(sampler2D tex, vec2 uv, vec2 texSize) {\n"
	"	vec2 texelSize = 1.0 / texSize;\n"
	"	vec2 samplePos = uv * texSize - 0.5;\n"
	"	vec2 baseTexel = floor(samplePos);\n"
	"	vec2 f = samplePos - baseTexel;\n"
	"\n"
	"	vec4 color = vec4(0.0);\n"
	"	float totalWeight = 0.0;\n"
	"\n"
	"	for (int y = -1; y <= 2; ++y) {\n"
	"		float wy = CatmullRomWeight(float(y) - f.y);\n"
	"		for (int x = -1; x <= 2; ++x) {\n"
	"			float wx = CatmullRomWeight(float(x) - f.x);\n"
	"			float w = wx * wy;\n"
	"			vec2 texel = baseTexel + vec2(float(x), float(y));\n"
	"			vec2 sampleUV = (texel + 0.5) * texelSize;\n"
	"			color += texture2D(tex, sampleUV) * w;\n"
	"			totalWeight += w;\n"
	"		}\n"
	"	}\n"
	"\n"
	"	return color / totalWeight;\n"
	"}\n"
	"\n"
	"void main() {\n"
	"	vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"	vec4 color = SampleTextureCatmullRom(textureSampler, textureUV, textureSize);\n"
	"	gl_FragColor = vec4(clamp(color.rgb, 0.0, 1.0), color.a);\n"
	"}\n"
};

static const char g_shaderFragmentTextureHQ2X[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"\n"
	"void main() {\n"
	"	vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"\n"
	"	const float edgeThreshold = 0.18;\n"
	"	const float blendStrength = 0.45;\n"
	"\n"
	"	vec2 texelSize = 1.0 / textureSize;\n"
	"\n"
	"	vec3 c  = texture2D(textureSampler, textureUV).rgb;\n"
	"	vec3 n  = texture2D(textureSampler, textureUV + vec2( 0.0,  texelSize.y)).rgb;\n"
	"	vec3 s  = texture2D(textureSampler, textureUV + vec2( 0.0, -texelSize.y)).rgb;\n"
	"	vec3 e  = texture2D(textureSampler, textureUV + vec2( texelSize.x,  0.0)).rgb;\n"
	"	vec3 w  = texture2D(textureSampler, textureUV + vec2(-texelSize.x,  0.0)).rgb;\n"
	"	vec3 ne = texture2D(textureSampler, textureUV + vec2( texelSize.x,  texelSize.y)).rgb;\n"
	"	vec3 nw = texture2D(textureSampler, textureUV + vec2(-texelSize.x,  texelSize.y)).rgb;\n"
	"	vec3 se = texture2D(textureSampler, textureUV + vec2( texelSize.x, -texelSize.y)).rgb;\n"
	"	vec3 sw = texture2D(textureSampler, textureUV + vec2(-texelSize.x, -texelSize.y)).rgb;\n"
	"\n"
	"	vec3 lumaWeights = vec3(0.299, 0.587, 0.114);\n"
	"\n"
	"	float lc  = dot(c,  lumaWeights);\n"
	"	float ln  = dot(n,  lumaWeights);\n"
	"	float ls  = dot(s,  lumaWeights);\n"
	"	float le  = dot(e,  lumaWeights);\n"
	"	float lw  = dot(w,  lumaWeights);\n"
	"	float lne = dot(ne, lumaWeights);\n"
	"	float lnw = dot(nw, lumaWeights);\n"
	"	float lse = dot(se, lumaWeights);\n"
	"	float lsw = dot(sw, lumaWeights);\n"
	"\n"
	"	float edgeNS = abs(ln - ls);\n"
	"	float edgeEW = abs(le - lw);\n"
	"	float edgeNE_SW = abs(lne - lsw);\n"
	"	float edgeNW_SE = abs(lnw - lse);\n"
	"\n"
	"	vec3 result = c;\n"
	"\n"
	"	if (edgeNE_SW > edgeThreshold && edgeNE_SW > edgeNW_SE) {\n"
	"		vec3 diagonal = 0.5 * (ne + sw);\n"
	"		result = mix(result, diagonal, blendStrength);\n"
	"	}\n"
	"\n"
	"	if (edgeNW_SE > edgeThreshold && edgeNW_SE > edgeNE_SW) {\n"
	"		vec3 diagonal = 0.5 * (nw + se);\n"
	"		result = mix(result, diagonal, blendStrength);\n"
	"	}\n"
	"\n"
	"	if (edgeNS > edgeThreshold && edgeNS > edgeEW) {\n"
	"		vec3 horizontal = 0.5 * (e + w);\n"
	"		result = mix(result, horizontal, blendStrength * 0.35);\n"
	"	}\n"
	"\n"
	"	if (edgeEW > edgeThreshold && edgeEW > edgeNS) {\n"
	"		vec3 vertical = 0.5 * (n + s);\n"
	"		result = mix(result, vertical, blendStrength * 0.35);\n"
	"	}\n"
	"\n"
	"	result = mix(c, result, 0.75);\n"
	"	gl_FragColor = vec4(clamp(result, 0.0, 1.0), 1.0);\n"
	"}\n"
};

static const char g_shaderFragmentTextureHQ4X[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"\n"
	"void main() {\n"
	"	vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"\n"
	"	float mx = 1.0;\n"
	"	const float k = -1.10;\n"
	"	const float max_w = 0.75;\n"
	"	const float min_w = 0.03;\n"
	"	const float lum_add = 0.33;\n"
	"\n"
	"	vec4 color = texture2D(textureSampler, textureUV);\n"
	"	vec3 c = color.xyz;\n"
	"\n"
	"	float x = 0.5 / textureSize.x;\n"
	"	float y = 0.5 / textureSize.y;\n"
	"\n"
	"	const vec3 dt = vec3(1.0, 1.0, 1.0);\n"
	"\n"
	"	vec2 dg1 = vec2( x, y);\n"
	"	vec2 dg2 = vec2(-x, y);\n"
	"\n"
	"	vec2 sd1 = dg1 * 0.5;\n"
	"	vec2 sd2 = dg2 * 0.5;\n"
	"\n"
	"	vec2 ddx = vec2(x, 0.0);\n"
	"	vec2 ddy = vec2(0.0, y);\n"
	"\n"
	"	vec4 t1 = vec4(textureUV - sd1, textureUV - ddy);\n"
	"	vec4 t2 = vec4(textureUV - sd2, textureUV + ddx);\n"
	"	vec4 t3 = vec4(textureUV + sd1, textureUV + ddy);\n"
	"	vec4 t4 = vec4(textureUV + sd2, textureUV - ddx);\n"
	"	vec4 t5 = vec4(textureUV - dg1, textureUV - dg2);\n"
	"	vec4 t6 = vec4(textureUV + dg1, textureUV + dg2);\n"
	"\n"
	"	vec3 i1 = texture2D(textureSampler, t1.xy).xyz;\n"
	"	vec3 i2 = texture2D(textureSampler, t2.xy).xyz;\n"
	"	vec3 i3 = texture2D(textureSampler, t3.xy).xyz;\n"
	"	vec3 i4 = texture2D(textureSampler, t4.xy).xyz;\n"
	"\n"
	"	vec3 o1 = texture2D(textureSampler, t5.xy).xyz;\n"
	"	vec3 o3 = texture2D(textureSampler, t6.xy).xyz;\n"
	"	vec3 o2 = texture2D(textureSampler, t5.zw).xyz;\n"
	"	vec3 o4 = texture2D(textureSampler, t6.zw).xyz;\n"
	"\n"
	"	vec3 s1 = texture2D(textureSampler, t1.zw).xyz;\n"
	"	vec3 s2 = texture2D(textureSampler, t2.zw).xyz;\n"
	"	vec3 s3 = texture2D(textureSampler, t3.zw).xyz;\n"
	"	vec3 s4 = texture2D(textureSampler, t4.zw).xyz;\n"
	"\n"
	"	float ko1 = dot(abs(o1 - c), dt);\n"
	"	float ko2 = dot(abs(o2 - c), dt);\n"
	"	float ko3 = dot(abs(o3 - c), dt);\n"
	"	float ko4 = dot(abs(o4 - c), dt);\n"
	"\n"
	"	float k1 = min(dot(abs(i1 - i3), dt), max(ko1, ko3));\n"
	"	float k2 = min(dot(abs(i2 - i4), dt), max(ko2, ko4));\n"
	"\n"
	"	float w1 = k2;\n"
	"	if (ko1 > 0.0001 && ko3 < ko1) {\n"
	"		w1 *= ko3 / ko1;\n"
	"	}\n"
	"\n"
	"	float w2 = k1;\n"
	"	if (ko2 > 0.0001 && ko4 < ko2) {\n"
	"		w2 *= ko4 / ko2;\n"
	"	}\n"
	"\n"
	"	float w3 = k2;\n"
	"	if (ko3 > 0.0001 && ko1 < ko3) {\n"
	"		w3 *= ko1 / ko3;\n"
	"	}\n"
	"\n"
	"	float w4 = k1;\n"
	"	if (ko4 > 0.0001 && ko2 < ko4) {\n"
	"		w4 *= ko2 / ko4;\n"
	"	}\n"
	"\n"
	"	c = (w1 * o1 + w2 * o2 + w3 * o3 + w4 * o4 + 0.001 * c) / (w1 + w2 + w3 + w4 + 0.001);\n"
	"\n"
	"	w1 = k * dot(abs(i1 - c) + abs(i3 - c), dt) / (0.125 * dot(i1 + i3, dt) + lum_add);\n"
	"	w2 = k * dot(abs(i2 - c) + abs(i4 - c), dt) / (0.125 * dot(i2 + i4, dt) + lum_add);\n"
	"	w3 = k * dot(abs(s1 - c) + abs(s3 - c), dt) / (0.125 * dot(s1 + s3, dt) + lum_add);\n"
	"	w4 = k * dot(abs(s2 - c) + abs(s4 - c), dt) / (0.125 * dot(s2 + s4, dt) + lum_add);\n"
	"\n"
	"	w1 = clamp(w1 + mx, min_w, max_w);\n"
	"	w2 = clamp(w2 + mx, min_w, max_w);\n"
	"	w3 = clamp(w3 + mx, min_w, max_w);\n"
	"	w4 = clamp(w4 + mx, min_w, max_w);\n"
	"\n"
	"	color = vec4((w1 * (i1 + i3) + w2 * (i2 + i4) + w3 * (s1 + s3) + w4 * (s2 + s4) + c) / (2.0 * (w1 + w2 + w3 + w4) + 1.0), color.a);\n"
	"	gl_FragColor = vec4(clamp(color.rgb, 0.0, 1.0), color.a);\n"
	"}\n"
};

static const char g_shaderFragmentTextureBicubicLagrange[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"\n"
	"vec3 CubicLagrange(vec3 A, vec3 B, vec3 C, vec3 D, float t) {\n"
	"	const float x0 = -1.0;\n"
	"	const float x1 =  0.0;\n"
	"	const float x2 =  1.0;\n"
	"	const float x3 =  2.0;\n"
	"\n"
	"	return\n"
	"		A * ((t - x1) / (x0 - x1) * (t - x2) / (x0 - x2) * (t - x3) / (x0 - x3)) +\n"
	"		B * ((t - x0) / (x1 - x0) * (t - x2) / (x1 - x2) * (t - x3) / (x1 - x3)) +\n"
	"		C * ((t - x0) / (x2 - x0) * (t - x1) / (x2 - x1) * (t - x3) / (x2 - x3)) +\n"
	"		D * ((t - x0) / (x3 - x0) * (t - x1) / (x3 - x1) * (t - x2) / (x3 - x2));\n"
	"}\n"
	"\n"
	"vec3 BicubicLagrangeTextureSample(sampler2D tex, vec2 uv, vec2 texSize) {\n"
	"	vec2 texelSize = 1.0 / texSize;\n"
	"	vec2 pixel = uv * texSize - 0.5;\n"
	"	vec2 baseTexel = floor(pixel);\n"
	"	vec2 frac = fract(pixel);\n"
	"\n"
	"	vec3 C00 = texture2D(tex, (baseTexel + vec2(-1.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C10 = texture2D(tex, (baseTexel + vec2( 0.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C20 = texture2D(tex, (baseTexel + vec2( 1.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C30 = texture2D(tex, (baseTexel + vec2( 2.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 C01 = texture2D(tex, (baseTexel + vec2(-1.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C11 = texture2D(tex, (baseTexel + vec2( 0.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C21 = texture2D(tex, (baseTexel + vec2( 1.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C31 = texture2D(tex, (baseTexel + vec2( 2.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 C02 = texture2D(tex, (baseTexel + vec2(-1.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C12 = texture2D(tex, (baseTexel + vec2( 0.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C22 = texture2D(tex, (baseTexel + vec2( 1.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C32 = texture2D(tex, (baseTexel + vec2( 2.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 C03 = texture2D(tex, (baseTexel + vec2(-1.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C13 = texture2D(tex, (baseTexel + vec2( 0.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C23 = texture2D(tex, (baseTexel + vec2( 1.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C33 = texture2D(tex, (baseTexel + vec2( 2.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 CP0X = CubicLagrange(C00, C10, C20, C30, frac.x);\n"
	"	vec3 CP1X = CubicLagrange(C01, C11, C21, C31, frac.x);\n"
	"	vec3 CP2X = CubicLagrange(C02, C12, C22, C32, frac.x);\n"
	"	vec3 CP3X = CubicLagrange(C03, C13, C23, C33, frac.x);\n"
	"\n"
	"	return CubicLagrange(CP0X, CP1X, CP2X, CP3X, frac.y);\n"
	"}\n"
	"\n"
	"void main() {\n"
	"	vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"	vec3 color = BicubicLagrangeTextureSample(textureSampler, textureUV, textureSize);\n"
	"	gl_FragColor = vec4(clamp(color, 0.0, 1.0), 1.0);\n"
	"}\n"
};

static const char g_shaderFragmentTextureBicubicHermite[] = {
	"uniform sampler2D textureSampler;\n"
	"uniform vec2 textureSize;\n"
	"uniform vec2 imageSize;\n"
	"varying vec2 vTexCoord;\n"
	"\n"
	"vec3 CubicHermite(vec3 A, vec3 B, vec3 C, vec3 D, float t) {\n"
	"	float t2 = t * t;\n"
	"	float t3 = t2 * t;\n"
	"	vec3 a = -A / 2.0 + (3.0 * B) / 2.0 - (3.0 * C) / 2.0 + D / 2.0;\n"
	"	vec3 b = A - (5.0 * B) / 2.0 + 2.0 * C - D / 2.0;\n"
	"	vec3 c = -A / 2.0 + C / 2.0;\n"
	"	vec3 d = B;\n"
	"	return a * t3 + b * t2 + c * t + d;\n"
	"}\n"
	"\n"
	"vec3 BicubicHermiteTextureSample(sampler2D tex, vec2 uv, vec2 texSize) {\n"
	"	vec2 texelSize = 1.0 / texSize;\n"
	"	vec2 pixel = uv * texSize - 0.5;\n"
	"	vec2 baseTexel = floor(pixel);\n"
	"	vec2 frac = fract(pixel);\n"
	"\n"
	"	vec3 C00 = texture2D(tex, (baseTexel + vec2(-1.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C10 = texture2D(tex, (baseTexel + vec2( 0.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C20 = texture2D(tex, (baseTexel + vec2( 1.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C30 = texture2D(tex, (baseTexel + vec2( 2.0, -1.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 C01 = texture2D(tex, (baseTexel + vec2(-1.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C11 = texture2D(tex, (baseTexel + vec2( 0.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C21 = texture2D(tex, (baseTexel + vec2( 1.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C31 = texture2D(tex, (baseTexel + vec2( 2.0,  0.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 C02 = texture2D(tex, (baseTexel + vec2(-1.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C12 = texture2D(tex, (baseTexel + vec2( 0.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C22 = texture2D(tex, (baseTexel + vec2( 1.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C32 = texture2D(tex, (baseTexel + vec2( 2.0,  1.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 C03 = texture2D(tex, (baseTexel + vec2(-1.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C13 = texture2D(tex, (baseTexel + vec2( 0.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C23 = texture2D(tex, (baseTexel + vec2( 1.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"	vec3 C33 = texture2D(tex, (baseTexel + vec2( 2.0,  2.0) + 0.5) * texelSize).rgb;\n"
	"\n"
	"	vec3 CP0X = CubicHermite(C00, C10, C20, C30, frac.x);\n"
	"	vec3 CP1X = CubicHermite(C01, C11, C21, C31, frac.x);\n"
	"	vec3 CP2X = CubicHermite(C02, C12, C22, C32, frac.x);\n"
	"	vec3 CP3X = CubicHermite(C03, C13, C23, C33, frac.x);\n"
	"\n"
	"	return CubicHermite(CP0X, CP1X, CP2X, CP3X, frac.y);\n"
	"}\n"
	"\n"
	"void main() {\n"
	"	vec2 imageUV = vTexCoord;\n"
	"	vec2 textureUV = imageUV * imageSize / textureSize;\n"
	"	vec3 color = BicubicHermiteTextureSample(textureSampler, textureUV, textureSize);\n"
	"	gl_FragColor = vec4(clamp(color, 0.0, 1.0), 1.0);\n"
	"}\n"
};

#endif // SHADERS_H