#pragma once

#define PRINT_QUEUE_INFOS 0
#define PRINT_FRAME_UPLOAD_INFOS 0
#define PRINT_MEMORY_STATS 0
#define PRINT_FRAME_DROPS 1
#define PRINT_VIDEO_REFRESH 0
#define PRINT_VIDEO_DELAY 0
#define PRINT_CLOCKS 0
#define PRINT_PTS 0
#define PRINT_FPS 0

#define USE_HARDWARE_RENDERING 0
#define USE_HARDWARE_IMAGE_FORMAT_DECODING 1
#define USE_FFMPEG_STATIC_LINKING 0
#define USE_GL_PBO 1
#define USE_GL_RECTANGLE_TEXTURES 1
#define USE_FFMPEG_SOFTWARE_CONVERSION 1
#define USE_FLIP_V_PICTURE_IN_SOFTWARE 1